### ISSUE TITLE
Bug: Taux de TVA non repris lors de l'ajout d'un produit/service

### ISSUE THREAD

**Issue by philippe-opendsi** [ATM-Consulting/dolibarr_module_searchproductcategory#7]
Bonjour
En testant ce module, je constate que le Taux de TVA n'est pas repris lorsqu'on ajoute un produit via l'arborescence du bas (voir copie écran).
![selection_343](https://user-images.githubusercontent.com/17143975/39122898-821b3920-46f6-11e8-8248-bccbbaf09f3e.jpg)
Dans script/interface.php la variable $txtva est reçue à vide (ligne 51)
Suggestion de correction 
alimentation de txtva par $p->tva_tx après le fetch ou alimenter la variable en amont via le js, mais là je vous laisse faire :-)
Merci

**Comment by atm-gauthier** [comment]
Bonjour Philippe,

Merci pour cette remarque, nous allons traiter ce point.

Gauthier.

**Comment by atm-gauthier** [comment]
La correction avait été faite dans la branche 1.0 que je viens de merger dans la master.
